### ISSUE TITLE
BhvButtonGroup里面 绑定cc.Component.EventHandler组件在最新版取不到component的值

### ISSUE THREAD

**Issue by Valdimirreap** [wsssheep/cocos_creator_mvvm_tools#3]
https://forum.cocos.com/t/2-1-0-component-eventhandler-component/70462

**Comment by wsssheep** [comment]
新版光绑定   hd.component = event.component; 是有问题，
还需要再加一行hd['_componentId'] = event['_componentId']; 
代码中已修复。
